### ISSUE TITLE
Access to SCI context from SCITTLE

### ISSUE THREAD

**Issue by elias94** [babashka/scittle#21]
On a page without clojurescript, I'm importing `scittle` from the CDN and loading the `cljs` script using 

```html
<script type="application/x-scittle" src="/assets/cljs/script.cljs"></script>
```

This is the portion of `script.cljs` interested where I'm finding all the `code` blocks with `language-clojure` and I replace them with a new instance of CodeMirror 5. The output component is composed by the CodeMirror code above and the code  output evaluated using `js/scittle.core.eval_string` below. [screenshot](https://user-images.githubusercontent.com/8095533/155862497-27b0adb9-9c8a-4857-b060-6e47d1447f5b.png)

If the `eval_string` output is `renderable?`, so is `hiccup` code, I want to render it in the output section below. Is working correctly if I the code evaluation returns a static component and I simply render it: `[:div res]`.

If is not `renderable?` simply print the value transformed in a string.
 
```clojure
(require '[reagent.core :as r]
         '[reagent.dom :as rdom]
         '[clojure.string :as string])

(defn editor
  [id state]
  (let [lines (string/split-lines @state)
        cm (.fromTextArea  js/CodeMirror
                           (.getElementById js/document id)
                           #js {:mode "clojure"
                                :theme "gruvbox"
                                :lineNumbers true
                                :smartIndent true
                                :tabSize 2})]
    (.on cm "change" (fn [_ _] (reset! state (.getValue cm))))
    (.setSize cm "auto" "auto")))

(defn renderable-element?
  [elem]
  (and (vector? elem)
       (keyword? (first elem))
       (not= (str (first elem)) ":")
       (not (string/includes? (str (first elem)) "/"))
       (not (re-matches #"[0-9]+" (name (first elem))))
       (not (re-matches #".*[\W]+" (name (first elem))))))

(defn renderable?
  [elem]
  (when (or (renderable-element? elem) (seq? elem))
    (let [[k props content] elem
          [props content] (if (and (nil? content)
                                   (not (map? props)))
                            [nil props]
                            [props content])]
      (cond
        (seq? elem) (seq? (filter renderable? elem))
        (seq? content) (seq? (filter renderable? content))
        :else (or (renderable-element? content)
                  (renderable-element? elem)
                  (string? content)
                  (number? content))))))

(defn result-component
  [state]
  (fn [state]
    (let [res (try (js/scittle.core.eval_string @state)
                   (catch :default e
                     {:error (.-message e)}))
          error? (contains? res :error)]
      [:div.result
       [:pre
        (if (renderable? res)
          [:div res]
          [:<>
           [:div (if error? "Error:" "Output:")]
           [:code
            (str (if error? (:error res) res))]])]])))

(defn run-clj
  [elem]
  (let [id (gensym "src-")
        src-str (.-innerText elem)
        child (first (.-childNodes elem))
        state (r/atom (string/trim-newline src-str))]
    (rdom/render [:textarea {:id id :rows 1} src-str] child)
    (editor id state)
    (rdom/render [result-component state] child)))

(defn run-editor []
  (let [clj-blocks (vec (.getElementsByClassName js/document
                                                 "language-clojure"))]
    (mapv run-clj clj-blocks)))

(run-editor)
```

The problem arises if in the code block there's more complex code that needs to interact with the context as:

```clojure
(def counter (r/atom 0))

(defn view []
  [:div
   [:p {:class ["text-sm" "text-gray-300" "mb-2"]}
    (str "Clicks: " @counter)]
   [:button
    {:class ["cursor-pointer"
             "border"
             "border-gray-500"
             "py-1"
             "px-2"
             "rounded-md"]
     :on-click #(swap! counter inc)}
    "Click me"]])

(view)
```

In this case if I simply render the output of `view`, it doesn't have access to the atom `counter`. To solve this I thought about using 
`(rdom/render [view] (.getElementById js/document "render-output"))` and it works correctly rendering the element. The problem is this. If I have multiple code blocks, every single one of them needs a different output element, not a single `<div id=render-output>`. 

So sci should generate a `(random-uuid)` and create a `div` with that id. After in some way maybe using a macro that replace `(render [view])` with `(rdom/render [view] (.getElementById js/document random-uuid)` or using a `sci/var` in some way.
Of maybe doing something like `(js/scittle.core.eval_string @state #js{:namespace {'user {'render my-render-fn}}})`.

**Comment by borkdude** [comment]
@elias94 I still have trouble understanding the problem, maybe I'm missing something.

> If I have multiple code blocks, every single one of them needs a different output element

Why don't you iterate over the code blocks and render in each corresponding output element? If this works for 1 input/output element pair, I don't see why you need access to SCI's ctx to make it work for multiple input/output element pairs?

**Comment by elias94** [comment]
I created an ugly version in codesandbox:

https://codesandbox.io/s/eager-antonelli-udn5ic?file=/index.html

If I use a reagent atom I need to use `rdom/render` to render the code entirely and not only the hiccup from the component.
In the example is working because I explicitly used a DOM element `<div id="render-output"></div>` into `(rdom/render [view] (.getElementById js/document "render-output"))`. But I don't want the code to specify an input, it should be automatic. If I have multiple code blocks with a reagent atom, each of them should be rendered into a different div.

So what I thought is creating a `div` with a random uuid and using a custom `render` function/macro to do `(rdom/render [view] (.getElementById js/document random-uuid))`. Maybe there's a more simple way to accomplish it, I just don't see it :(

**Comment by borkdude** [comment]
@elias94 The link isn't working for me. Can you make a repository with the HTML? Then I'll check it out locally.

**Comment by borkdude** [comment]
Discussed a different solution with @elias94 on Slack.
