### ISSUE TITLE
In-browser REPL for dev

### ISSUE THREAD

**Issue by divs1210** [babashka/scittle#22]
It would be great if we could have a REPL console that could be turned on during dev.

Example, running `cljs_repl()` in the browser console would load the scittle REPL, possibly with the current state loaded.

**Comment by borkdude** [comment]
@divs1210 Interesting idea. 

Note that you can already evaluate expressions using `scittle.core.eval_string` in the browser console. So together with a text intput you might already come a long way.

**Comment by divs1210** [comment]
Thanks! Yes, that's what I ended up doing. 

Also, making a repl might be tricky because it will require a blocking prompt.

Not sure if it's worth the trouble.

**Comment by borkdude** [comment]
@divs1210 I'm already working on a in-browser nREPL solution:

https://twitter.com/borkdude/status/1511357850756521985

I hope to bring this to scittle within a few weeks.

**Comment by borkdude** [comment]
Meanwhile, something like livejs may also help.
