### ISSUE TITLE
No position info for "Could not resolve symbol" error.

### ISSUE THREAD

**Issue by jurjanpaul** [babashka/scittle#34]
I'm finding that some errors in Scittle scripts are not logged with the same quality of context (position info) as others.

Exceptions thrown during the evaluation phase are logged with position info, and the same is true for errors occurring during the parse phase, e.g. "EOF while reading, expected ) to match ( at [2,1]".

But the following script that causes an error that is marked with 'Phase: analysis' unfortunately does not provide position information:

```
<html>
  <head>
    <script src="https://cdn.jsdelivr.net/npm/scittle@0.2.8/dist/scittle.js" type="application/javascript"></script>
    <script type="application/x-scittle">
(defn f [x]
  (inc n)) ; 'typo' that causes "Could not resolve symbol: n" error.
    </script>
  </head>
  <body>
  </body>
</html>
```  

(The Clojure REPL does provide position info for an error like this, but incidently Babashka doesn't either, which suggests that this might actually be a SCI limitation.)

**Comment by borkdude** [comment]
Going to look at this today.

**Comment by borkdude** [comment]
Can reproduce the same problem with bb.

**Comment by borkdude** [comment]
<img width="653" alt="Screenshot 2022-08-31 at 17 21 39" src="https://user-images.githubusercontent.com/284934/187716400-468cfdc3-0d24-4571-9dc7-9908513128ec.png">

**Comment by jurjanpaul** [comment]
Excellent, thanks! Now indeed gets the result I hoped for.
Good to see SCI itself being improved!
