### ISSUE TITLE
'localhost' is hardcoded as the hostname for the WebSocket connection

### ISSUE THREAD

**Issue by pyrmont** [babashka/scittle#48]
## Problem

I would like to be able to develop on one machine (Machine A) but view the webpage that includes Scittle on a different machine (Machine B). A scenario where this might occur is whether Machine B is a phone.

Currently, if you attempt to do this, an editor running on Machine A cannot connect to the nREPL session running on Machine B because `scittle.nrepl` hardcodes `"localhost"` as the hostname for the WebSocket connection:

https://github.com/babashka/scittle/blob/151ea479f3723ad68781b3d134e81bd1661d3f99/src/scittle/nrepl.cljs#L37-L39

## Solution

Use `(.-hostname (-.location js/window))` rather than `"localhost"`. This means that if Machine B has accessed the webpage using a hostname other than 'localhost', the nREPL connection will work as expected.

I am ready to submit a PR if this sounds acceptable.

**Comment by borkdude** [comment]
PR welcome
