### ISSUE TITLE
Support for `clojure.spec.alpha`?

### ISSUE THREAD

**Issue by refset** [babashka/scittle#54]
After looking at https://github.com/babashka/spec.alpha and the associated blog post I can see that getting `clojure.spec.alpha` working isn't a trivial matter in general, but I'm curious...what would need to happen for spec to be require-able and used from a Scittle script tag?

**Comment by borkdude** [comment]
It could be done as a built-in probably and compiled as an optional module. Can you tell more about your use case?

**Comment by borkdude** [comment]
In general I'd like to wait for spec non-alpha before I build anything in because maintaining two separate versions isn't great. Another option is to make babashka spec alpha compatible with SCI cljs so you can load it from source.

**Comment by refset** [comment]
Thanks for the fast response!

> Can you tell more about your use case?

I'd like to create an interactive demo page for a new (currently unreleased) library that has a single dependency on spec, which is used for some `conform`/`conformer` validation & transformations. I did start attempting to work with https://github.com/borkdude/cljs-showcase initially, but the trouble there is that this library also requires runtime `eval` access so I would need to pull in the self-hosted cljs compiler and figure out how to make that work. However that's feeling like the easier route at this point, or simply dropping the idea of ad-hoc interactivity in favour of using Clerk.

**Comment by borkdude** [comment]
> the trouble there is that this library also requires runtime eval access 

This is exactly what SCI can be used for? Or am I misunderstanding something?
What you want is probably a SCI configuration for clojure.spec.alpha that you can use along with your library. If you can publish things or make me a collaborator, I could try to take a look maybe.

**Comment by borkdude** [comment]
The difficulty with clojure.spec.alpha and `sci/copy-ns` is that copy-ns doesn't copy any macros since they live on the JVM side.

**Comment by refset** [comment]
> This is exactly what SCI can be used for? 

Yes, SCI would be more ideal, hence this issue :)

> If you can publish things or make me a collaborator, I could try to take a look maybe.

Done! (we're hoping to open it up next week)

> The difficulty with clojure.spec.alpha and sci/copy-ns is that copy-ns doesn't copy any macros since they live on the JVM side.

Interesting, I suspected this was the underlying blocker and I did see a lot of "macro" things in the SCI API but I guess none of those are relevant to this.

**Comment by borkdude** [comment]
I'll take a stab at making some of those spec macros work in SCI

**Comment by borkdude** [comment]
We ended up with:

https://github.com/borkdude/cljs-showcase/tree/trip

**Comment by borkdude** [comment]
More details:

``` clojure
(def tns (sci/create-ns 'juxt.trip.core))
(def trip-namespace (sci/copy-ns juxt.trip.core tns {:exclude-when-meta []}))

(ctx-store/swap-ctx! sci/merge-opts {:namespaces {'medley.core medley-ns
                                                  'juxt.trip.core trip-namespace}})

(set! cljs.core/*eval* #(sci/eval-form (ctx-store/get-ctx) %))
```
