### ISSUE TITLE
script/release.clj assumes that the gh-pages directory exists

### ISSUE THREAD

**Issue by daslu** [babashka/scittle#55]
When the `gh-pages` directory does not exist, `script/release.clj` copies an html file to a file named `gh-pages`, and then the following copy operations fail.

https://github.com/babashka/scittle/blob/11b7a56ab8073efd7e9e123b74f10bd38e6e4f16/script/release.clj#L6

**Comment by borkdude** [comment]
PR welcome. You can ensure a directory with `fs/create-dirs`
