### ISSUE TITLE
Using the latest sci.nrepl is not compatible with the current scittle.nrepl release

### ISSUE THREAD

**Issue by benjamin-asdf** [babashka/scittle#57]
A while ago we moved some nrepl handling logic into `scittle.nrepl`.

95740162d42bf4c9a2a17740c4eed07b0899229d

The latest `sci.nrepl` is not backwards compatible with the current scittle release.
(`describe` is not handled).

I forget the details right now but in order to have the server update (with eldoc) working
a fresh build of `scittle.nrepl` is needed.

This hypothesis would be falsified, if the current build already incorporates  
95740162d42bf4c9a2a17740c4eed07b0899229d.

**Comment by borkdude** [comment]
Would a new scittle release solve it?

**Comment by benjamin-asdf** [comment]
If my hypothesis is true, it should.

**Comment by borkdude** [comment]
should be fixed
