### ISSUE TITLE
error :  Could not resolve symbol: r/create-element  , or r/as-element

### ISSUE THREAD

**Issue by mikelemus27** [babashka/scittle#65]
i was trying to do  the example  from here :  https://cljdoc.org/d/reagent/reagent/1.1.1/doc/tutorials/interop-with-react

(defn integration []
  [:div
   [:div.foo "Hello " [:strong "world"]]

   (r/create-element "div"
                     #js{:className "foo"}
                     "Hello "
                     (r/create-element "strong"
                                        #js{}
                                        "world"))

   (r/create-element "div"
                     #js{:className "foo"}
                     "Hello "
                     (r/as-element [:strong "world"]))

   [:div.foo "Hello " (r/create-element "strong"
                                        #js{}
                                        "world")]])
****************************************
and i got this error
![image](https://github.com/babashka/scittle/assets/146947/71f0522d-68bc-4f6f-b3bb-ce705bb8f12e)
and i have the require like this 
![image](https://github.com/babashka/scittle/assets/146947/90503823-1dd6-4796-b6a7-a80377561c22)

is posible that  the implementation of reagent  in scittle  do not include  that function?

**Comment by borkdude** [comment]
Yes. We should include it here:

https://github.com/babashka/sci.configs/blob/main/src/sci/configs/reagent/reagent.cljs and them bump sci.configs here.

**Comment by borkdude** [comment]
Question: why would you use `create-element` if you can use hiccup? Still, happy to include this.

**Comment by borkdude** [comment]
Fixed on master
