### ISSUE TITLE
repl server OR browser-repl connect code mixes zipmap indices on vectors of 32 count and above 

### ISSUE THREAD

**Issue by tecumsehcommunications** [babashka/scittle#79]
Scittle version:  0.6.17
Squint version: 0.7.105

The squint repl does not have this problem.  Only in the browser.

Steps to reproduce:

1:       (def vec1 (vec (range 33)))
          (doseq [x vec1] (println x))
          
2:       (def vec2 (vec (range 33)))
          (doseq [x vec2] (println x))
          
3:       (def amap (zipmap vec1 vec2))
          (doseq [ [x y] amap ] (println x y))
 

Output from steps 1 and 2 is as expected.  But output from #3 is:

0 0
32 32  <===
1 1
2 2
3 3
4 4
5 5
. . .  the rest is as it should be

Increasing the vector size past 33 results in an increasingly mixed up field of numbers.

**Comment by borkdude** [comment]
Clojure(Script) maps are not ordered.
