### ISSUE TITLE
is deftype supported within Scittle

### ISSUE THREAD

**Issue by kangaroolab** [babashka/scittle#80]
I couldn't find the exact info so like to clarify/confirm.

```
my testing:
(defprotocol IAdd
  (add-num [this y] "Add two numbers"))
(deftype Foo1 [x]
  IAdd
  (add-num [this y]
    (+ x y)))
(def f1 (Foo1. 1))
(.-x f1)
```

this doesn't return anything

**Comment by borkdude** [comment]
`deftype` is supported with user-defined protocols, but in Clojure you aren't supposed to access fields from deftypes via interop. If you want to do this, it's better to use `defrecord` + `(:x f1)`.
For accessing information from a deftype it's recommended to do this via the protocol as well:

```
(defprotocol IAdd
  (add-num [this y] "Add two numbers")
  (get-num [this]))

(deftype Foo1 [x]
  IAdd
  (add-num [this y]
    (+ x y))
  (get-num [this] x))

(def f1 (Foo1. 1))
(prn (get-num f1))
```

**Comment by kangaroolab** [comment]
thanks for the clarification and example.
