### ISSUE TITLE
how to require javascript library

### ISSUE THREAD

**Issue by schneiderlin** [babashka/scittle#83]
for reagent hook, I need to require ["react" :as react]. how to do that in scittle?

**Comment by borkdude** [comment]
In scittle you include react in a script tag:

``` clojure
<script crossorigin src="https://unpkg.com/react@17/umd/react.production.min.js"></script>
<script crossorigin src="https://unpkg.com/react-dom@17/umd/react-dom.production.min.js"></script>
```

This makes react available as a global: `js/React`, I believe. So you don't need to do this via require.
